const state={page:"dashboard",logged:false};
const docs=[
{name:"Factura_Proveedor_A_Agosto_2026.pdf",type:"Factura",area:"Financiera",owner:"Proveedor A",date:"15/08/2026",size:"1.2 MB",status:"Vigente"},
{name:"Contrato_Proveedor_A_2026.pdf",type:"Contrato",area:"Compras",owner:"Proveedor A",date:"03/01/2026",size:"2.4 MB",status:"Vigente"},
{name:"Contrato_Proveedor_B_2026.pdf",type:"Contrato",area:"Compras",owner:"Proveedor B",date:"20/02/2026",size:"2.1 MB",status:"Vigente"},
{name:"Reporte_Gastos_Agosto_2026.xlsx",type:"Reporte",area:"Financiera",owner:"Interno",date:"31/08/2026",size:"850 KB",status:"Vigente"},
{name:"Politica_Respaldos_CloudDoc.pdf",type:"Política",area:"Seguridad",owner:"Interno",date:"10/03/2026",size:"780 KB",status:"Vigente"},
{name:"Manual_Usuarios_CloudDoc.pdf",type:"Manual",area:"Administración",owner:"Interno",date:"05/04/2026",size:"1.6 MB",status:"Vigente"},
{name:"Factura_Proveedor_B_Julio_2026.pdf",type:"Factura",area:"Financiera",owner:"Proveedor B",date:"28/07/2026",size:"1.0 MB",status:"Vigente"},
{name:"Acta_Reunion_Direccion_2026.pdf",type:"Acta",area:"Administración",owner:"Interno",date:"12/06/2026",size:"620 KB",status:"Archivado"}
];
const users=[{name:"Ana Torres",email:"ana@clouddoc.demo",role:"Administrador",status:"Activo"},{name:"Carlos Gómez",email:"carlos@clouddoc.demo",role:"Empleado",status:"Activo"},{name:"Laura Pérez",email:"laura@clouddoc.demo",role:"Invitado",status:"Inactivo"}];
function el(html){const t=document.createElement("template");t.innerHTML=html.trim();return t.content.firstChild}
function render(){if(!state.logged){renderLogin();return}const root=document.getElementById("app");root.innerHTML=`<div class="app"><aside class="sidebar"><div class="logo">CloudDoc <small>IA</small></div><nav class="nav">${nav("dashboard","▣","Panel principal")}${nav("documents","▤","Documentos")}${nav("users","👥","Usuarios / Permisos")}${nav("security","🔐","Seguridad")}${nav("backups","☁","Respaldos")}${nav("assistant","✦","Asistente IA")}</nav><div class="sidebottom">Sistema de Gestión Documental<br>Prototipo académico · 2026</div></aside><main class="main"><div class="page">${pageContent()}</div></main></div>`;bind()}
function nav(id,icon,label){return `<button class="${state.page===id?'active':''}" data-page="${id}"><span>${icon}</span>${label}</button>`}
function renderLogin(){document.getElementById("app").innerHTML=`<div class="login"><div class="loginbox"><div class="loginbrand">CloudDoc</div><h1>Sistema de Gestión Documental</h1><p>Accede para administrar y consultar la información de tu organización.</p><div class="field"><label>Correo electrónico</label><input id="loginEmail" value="admin@smartinfo.com"></div><div class="field"><label>Contraseña</label><input id="loginPass" type="password" value="admin123"></div><label class="remember"><input type="checkbox" checked> Recordarme</label><button class="btn primary" id="loginBtn">Iniciar sesión</button><div class="demo">Credenciales de demostración: admin@smartinfo.com · admin123</div></div></div>`;document.getElementById("loginBtn").onclick=()=>{state.logged=true;state.page="dashboard";render();toast("Sesión iniciada correctamente")}}
function pageShell(title,desc,body){return `<div class="topbar"><div class="title"><h1>${title}</h1><p>${desc}</p></div><div class="userbox"><div><b>Administrador</b><small>admin@smartinfo.com</small></div><div class="avatar">A</div></div></div>${body}`}
function pageContent(){switch(state.page){case"documents":return pageShell("Gestión documental","Centraliza, organiza y consulta los documentos de la empresa.",documentsPage());case"users":return pageShell("Usuarios y permisos","Administra accesos y niveles de autorización.",usersPage());case"security":return pageShell("Seguridad","Controles para proteger la información almacenada.",securityPage());case"backups":return pageShell("Respaldos de datos","Supervisa las copias y la disponibilidad de la información.",backupsPage());case"assistant":return pageShell("Asistente inteligente","Consulta documentos utilizando lenguaje natural.",assistantPage());default:return pageShell("Panel principal","Vista general de la gestión documental de CloudDoc.",dashboardPage())}}
function dashboardPage(){return `<div class="grid g4">${stat("▤","128","Documentos almacenados")}${stat("📁","8","Áreas organizadas")}${stat("👥","12","Usuarios registrados")}${stat("☁","96%","Estado de respaldos")}</div><div style="height:18px"></div><div class="grid g2"><section class="card pad"><h2>Actividad reciente</h2><table><thead><tr><th>Documento</th><th>Acción</th><th>Fecha</th></tr></thead><tbody><tr><td>Factura_Proveedor_A_Agosto_2026.pdf</td><td><span class="badge green">Subido</span></td><td>Hoy · 09:42</td></tr><tr><td>Contrato_Proveedor_B_2026.pdf</td><td><span class="badge">Consultado</span></td><td>Hoy · 09:17</td></tr><tr><td>Reporte_Gastos_Agosto_2026.xlsx</td><td><span class="badge">Actualizado</span></td><td>Ayer · 16:08</td></tr></tbody></table></section><section class="card pad"><h2>Accesos rápidos</h2><div class="grid g2"><button class="btn secondary" onclick="go('documents')">▤ Ver documentos</button><button class="btn secondary" onclick="go('assistant')">✦ Consultar IA</button><button class="btn secondary" onclick="go('users')">👥 Gestionar usuarios</button><button class="btn secondary" onclick="go('backups')">☁ Revisar respaldos</button></div><div style="height:18px"></div><div class="notice"><b>Objetivo de CloudDoc</b><br>Centralizar la información, facilitar el acceso y reducir la pérdida y desorganización de documentos.</div></section></div><div style="height:18px"></div><section class="card pad"><h2>Distribución documental por área</h2><div class="grid g2">${bar("Financiera",42)}${bar("Compras",27)}${bar("Administración",18)}${bar("Seguridad",13)}</div></section>`}
function stat(icon,num,label){return `<section class="card stat"><div class="icon">${icon}</div><strong>${num}</strong><span>${label}</span></section>`}
function bar(label,pct){return `<div><div style="display:flex;justify-content:space-between;font-size:12px;margin-bottom:7px"><b>${label}</b><span class="muted">${pct}%</span></div><div class="bar"><i style="width:${pct}%"></i></div></div>`}
function documentsPage(){return `<div class="toolbar"><div class="search"><input id="docSearch" placeholder="Buscar por nombre, tipo, área o proveedor..."><button class="btn secondary" onclick="filterDocs()">Buscar</button></div><button class="btn primary" onclick="openUpload()">＋ Subir archivo</button></div><section class="card pad"><h2>Carpetas por área</h2><div class="foldergrid">${folder("📂","Financiera","34 documentos")}${folder("📂","Compras","22 documentos")}${folder("📂","Administración","18 documentos")}${folder("📂","Seguridad","11 documentos")}</div></section><div style="height:18px"></div><section class="card pad"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px"><h2>Documentos</h2><span class="small muted" id="docCount">${docs.length} resultados</span></div><table><thead><tr><th>Nombre</th><th>Tipo</th><th>Área</th><th>Fecha</th><th>Tamaño</th><th>Estado</th><th></th></tr></thead><tbody id="docRows">${docRows(docs)}</tbody></table></section>`}
function folder(icon,name,count){return `<div class="folder"><div class="foldericon">${icon}</div><b>${name}</b><small>${count}</small></div>`}
function docRows(list){return list.map((d,i)=>`<tr><td><b>${d.name}</b></td><td>${d.type}</td><td>${d.area}</td><td>${d.date}</td><td>${d.size}</td><td><span class="badge ${d.status==="Vigente"?"green":""}">${d.status}</span></td><td><button class="btn secondary" style="padding:7px 9px;font-size:11px" onclick="viewDoc(${i})">Ver</button></td></tr>`).join("")}
function filterDocs(){const q=document.getElementById("docSearch").value.toLowerCase().trim();const list=docs.filter(d=>(d.name+" "+d.type+" "+d.area+" "+d.owner).toLowerCase().includes(q));document.getElementById("docRows").innerHTML=docRows(list);document.getElementById("docCount").textContent=list.length+" resultados"}
function usersPage(){return `<div class="toolbar"><div class="kpis"><div class="kpi">12 usuarios</div><div class="kpi">3 roles</div><div class="kpi">2 niveles de acceso</div></div><button class="btn primary" onclick="addUser()">＋ Agregar usuario</button></div><section class="card pad"><h2>Usuarios registrados</h2><table><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>${users.map(u=>`<tr><td><b>${u.name}</b></td><td>${u.email}</td><td>${u.role}</td><td><span class="badge ${u.status==="Activo"?"green":"red"}">${u.status}</span></td><td><button class="btn secondary" style="padding:7px 9px;font-size:11px" onclick="toast('Permisos de ${u.name} abiertos')">Gestionar</button></td></tr>`).join("")}</tbody></table></section><div style="height:18px"></div><div class="grid g3">${roleCard("Administrador","Acceso total","Gestiona usuarios, documentos, seguridad y respaldos.")}${roleCard("Empleado","Acceso operativo","Consulta y modifica documentos autorizados.")}${roleCard("Invitado","Acceso limitado","Consulta únicamente información compartida.")}</div>`}
function roleCard(role,access,desc){return `<section class="card pad"><h3>${role}</h3><span class="badge">${access}</span><p class="small muted">${desc}</p></section>`}
function securityPage(){return `<div class="grid g3">${securityStat("Autenticación","Activa","Políticas de contraseña y control de acceso","green")}${securityStat("MFA","Recomendada","Aplicable a cuentas críticas","amber")}${securityStat("Auditoría","Activa","Registro de acciones de usuarios","green")}</div><div style="height:18px"></div><div class="grid g2"><section class="card pad"><h2>Control de acceso</h2><div class="flow">${flow("1","Definición de roles y permisos")}${flow("2","Principio de menor privilegio")}${flow("3","Restricción por área y documento")}${flow("4","Registro de quién hizo qué y cuándo")}</div></section><section class="card pad"><h2>Medidas de protección</h2><div class="notice">• Contraseñas robustas y revisión periódica.<br>• MFA para cuentas críticas.<br>• Cifrado de información en tránsito y reposo.<br>• Revisión periódica de accesos.<br>• Auditoría y trazabilidad.</div></section></div>`}
function securityStat(title,value,desc,type){return `<section class="card pad"><h3>${title}</h3><span class="badge ${type}">${value}</span><p class="small muted">${desc}</p></section>`}
function flow(n,t){return `<div class="flowstep"><div class="num">${n}</div><div>${t}</div></div>`}
function backupsPage(){return `<div class="grid g3">${stat("☁","96%","Estado general")}${stat("↻","7","Respaldos recientes")}${stat("✓","100%","Última prueba de restauración")}</div><div style="height:18px"></div><div class="grid g2"><section class="card pad"><h2>Estrategia de respaldo</h2>${bar("Incrementales diarios",82)}<div style="height:16px"></div>${bar("Completos semanales",100)}<div style="height:16px"></div>${bar("Retención histórica",74)}<div style="height:16px"></div><div class="notice">Se recomienda conservar copias fuera del sitio, cifrar los respaldos y realizar pruebas periódicas de restauración.</div></section><section class="card pad"><h2>Últimos respaldos</h2><table><thead><tr><th>Fecha</th><th>Tipo</th><th>Estado</th></tr></thead><tbody><tr><td>28/09/2026 02:00</td><td>Incremental</td><td><span class="badge green">Exitoso</span></td></tr><tr><td>27/09/2026 02:00</td><td>Incremental</td><td><span class="badge green">Exitoso</span></td></tr><tr><td>25/09/2026 02:00</td><td>Completo</td><td><span class="badge green">Exitoso</span></td></tr></tbody></table></section></div>`}
function assistantPage(){return `<div class="grid g2" style="grid-template-columns:1.5fr .8fr"><section class="card chat"><div class="chathead"><div class="bot">✦</div><div><b>CloudDoc Assistant</b><div class="small muted">Componente IA · base documental de demostración</div></div></div><div class="messages" id="messages"><div class="msg assistant"><div class="bubble">Hola. Soy el asistente de CloudDoc. Puedo ayudarte a localizar documentos y consultar información mediante lenguaje natural.<div class="result"><b>Ejemplos</b><div class="small muted">• ¿Dónde está la factura del proveedor A?<br>• Muéstrame los contratos vigentes<br>• ¿Qué documentos tiene el área financiera?</div></div></div></div></div><div class="composer"><div class="quick"><button onclick="quick('¿Dónde está la factura del proveedor A?')">Factura proveedor A</button><button onclick="quick('Muéstrame los contratos vigentes')">Contratos vigentes</button><button onclick="quick('¿Qué documentos tiene el área financiera?')">Área financiera</button></div><div class="composerrow"><input id="aiInput" placeholder="Escribe una consulta..." onkeydown="if(event.key==='Enter')sendAI()"><button class="btn primary" onclick="sendAI()">Consultar</button></div></div></section><div class="grid" style="align-content:start"><section class="card pad"><h2>Flujo del componente IA</h2><div class="flow">${flow("1","Consulta en lenguaje natural")}${flow("2","Procesamiento de la consulta")}${flow("3","Búsqueda sobre documentos y metadatos")}${flow("4","Selección de información relevante")}${flow("5","Respuesta al usuario")}</div></section><section class="card pad"><h2>Datos utilizados</h2><div class="notice"><b>Entrada:</b> pregunta del usuario.<br><b>Datos:</b> contenido y metadatos: nombre, fecha, tipo, área y proveedor.<br><b>Salida:</b> documentos relevantes e información contextual.</div></section><section class="card pad"><h2>Limitaciones del prototipo</h2><p class="small muted">Esta es una simulación funcional académica. En una implementación productiva, el módulo podría conectarse a un modelo de lenguaje, embeddings y una base vectorial.</p></section></div></div>`}
function sendAI(){const inp=document.getElementById("aiInput");if(!inp)return;const q=inp.value.trim();if(!q)return;addAI(q,"user");inp.value="";setTimeout(()=>{const r=answerAI(q);addAI(r.text,"assistant",r.results)},300)}
function quick(q){const i=document.getElementById("aiInput");i.value=q;sendAI()}
function addAI(text,who,results=[]){const m=document.getElementById("messages");const w=el(`<div class="msg ${who}"><div class="bubble">${text}</div></div>`);if(results.length){const box=el(`<div class="result"><b>Documentos relevantes</b></div>`);results.forEach(d=>{box.insertAdjacentHTML("beforeend",`<div class="doc"><div><b>${d.name}</b><small>${d.type} · ${d.area} · ${d.owner} · ${d.date}</small></div><small>${Math.min(99,70+d.score*4)}%</small></div>`)});w.querySelector(".bubble").appendChild(box)}m.appendChild(w);m.scrollTop=999999}
function answerAI(q){const t=q.toLowerCase();let list=docs.map(d=>{let score=0;const s=(d.name+" "+d.type+" "+d.area+" "+d.owner+" "+d.status).toLowerCase();["factura","contrato","financiera","compras","proveedor","vigente","seguridad","usuario","documento","reporte"].forEach(k=>{if(t.includes(k)&&s.includes(k))score+=2});return {...d,score}}).filter(d=>d.score>0).sort((a,b)=>b.score-a.score).slice(0,3);if(!list.length)return{text:"No encontré documentos relevantes en la base de demostración. Intenta con facturas, contratos, proveedores, finanzas, seguridad o usuarios.",results:[]};let lead=t.includes("factura")?"Encontré información relacionada con la factura.":t.includes("contrato")?"Encontré los contratos relacionados con la consulta.":t.includes("financ")?"Encontré documentos del área financiera.":"Encontré información relacionada con tu consulta.";return{text:lead+" Estos son los resultados más relevantes:",results:list}}
function bind(){document.querySelectorAll("[data-page]").forEach(b=>b.onclick=()=>go(b.dataset.page))}function go(p){state.page=p;render()}
function openUpload(){document.getElementById("app").appendChild(el(`<div class="modal" id="modal"><div class="modalbox"><div class="modalhead"><h2>Subir documento</h2><button class="close" onclick="this.closest('.modal').remove()">✕</button></div><div class="field"><label>Archivo</label><input type="file"></div><div class="field"><label>Área</label><select><option>Financiera</option><option>Compras</option><option>Administración</option><option>Seguridad</option></select></div><button class="btn primary" onclick="this.closest('.modal').remove();toast('Documento agregado al prototipo')">Guardar documento</button></div></div>`))}
function viewDoc(i){const d=docs[i];document.getElementById("app").appendChild(el(`<div class="modal"><div class="modalbox"><div class="modalhead"><h2>Detalle del documento</h2><button class="close" onclick="this.closest('.modal').remove()">✕</button></div><p><b>${d.name}</b></p><div class="notice">Tipo: ${d.type}<br>Área: ${d.area}<br>Propietario: ${d.owner}<br>Fecha: ${d.date}<br>Tamaño: ${d.size}<br>Estado: ${d.status}</div></div></div>`))}
function addUser(){toast("Formulario de nuevo usuario disponible en la versión de demostración")}
function toast(msg){const t=el(`<div class="toast">${msg}</div>`);document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}render();
